import type { Metadata } from "next";
import { Bigshot_One } from "next/font/google";
import "./globals.css";
import { Suspense, useEffect } from "react";
import { authOptions } from "./api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth";
import { Providers } from "./providers";
import { Header } from "@/components/Header";
import { getRooms, removeUserFromRoom } from "@/instance";

const inter = Bigshot_One({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "The Switch",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header session={session} />
        <Providers session={session}>
          <Suspense fallback={null}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}
